// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedtheCustomerModelClassandaddedaFirstNameandLastNameProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedtheCustomerModelClassandaddedaFirstNameandLastNameProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201901032148010_Edited the Customer Model Class and added a First Name and Last Name Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
