// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedaPickupStausModelClassthatconfirmsthePickup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedaPickupStausModelClassthatconfirmsthePickup));
        
        string IMigrationMetadata.Id
        {
            get { return "201901042303511_Added a Pickup Staus Model Class that confirms the Pickup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
