// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updaedthecustomermodelandaddedanewpropertythatwasreadonlyandsamewiththepickupbill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updaedthecustomermodelandaddedanewpropertythatwasreadonlyandsamewiththepickupbill));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090058431_Updaed the customer model and added a new property that was read only, and same with the pickupbill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
