// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editedthecustomermodelclassandchangedthepickupbilltotypedouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedthecustomermodelclassandchangedthepickupbilltotypedouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201901042352469_edited the customer model class and changed the pickup bill to type double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
